pipeline {
    agent any

    tools {
        maven 'Maven-3.8.4'   // Configure Maven in Jenkins (Manage Jenkins > Global Tool Configuration)
        jdk 'Java-21'     // Use correct JDK version (match your project)
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Shiva-shiv/Rest-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                // Example: copy JAR to server
                sh '''
                echo "Deploying application..."
                cp target/*.jar /opt/deployment/
                '''
                // If using Docker:
                // sh 'docker build -t sb-user-rest-app .'
                // sh 'docker run -d -p 8080:8080 sb-user-rest-app'
            }
        }
    }
}
