pipeline {
    agent any
    
    tools {
        jdk 'jdk-21'
        maven 'maven-3.8.4'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Shiva-shiv/Rest-app.git', branch: 'main'
            }
        }

        stage('Build & Package') {
            steps {
                dir('Sb-User-Rest-App-Application') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Verify Artifact') {
            steps {
                dir('Sb-User-Rest-App-Application') {
                    sh 'ls -lh target/'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Sb-User-Rest-App-Application') {
                    sh 'docker build -t rest-app:latest .'
                }
            }
        }

        stage('Run App') {
            steps {
                dir('Sb-User-Rest-App-Application') {
                    sh 'docker run -d -p 8080:8080 --name rest-app-container rest-app:latest || true'
                }
            }
        }
    }
}
